use homework_1;

ALTER TABLE developers 
	ADD SALARY INT(6) DEFAULT NULL
	AFTER DEVELOPER_NAME;
    
UPDATE developers SET SALARY=2000 WHERE DEVELOPER_NAME='Vasya';
UPDATE developers SET SALARY=200 WHERE DEVELOPER_NAME='Tanya';
UPDATE developers SET SALARY=2100 WHERE DEVELOPER_NAME='Olya';
UPDATE developers SET SALARY=1000 WHERE DEVELOPER_NAME='Inna';
 